# Generated by Django 3.2.1 on 2021-05-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('imgurl', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
