# Generated by Django 3.2.1 on 2021-05-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.CharField(help_text='코멘트를 입력해 주세요. 240자 제한.', max_length=240, verbose_name='코멘트'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.FloatField(default=2.5, verbose_name='평점'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
