# Generated by Django 3.2.1 on 2021-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysisapp', '0002_auto_20210511_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.CharField(help_text='코멘트를 입력해 주세요. 240자 제한.', max_length=240, null=True, verbose_name='코멘트'),
        ),
    ]
