# Generated by Django 3.2.1 on 2021-05-08 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_pk', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('gender', models.SmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Not to disclose')], default=2)),
                ('nickname', models.CharField(max_length=20, null=True, unique=True)),
                ('bio', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(null=True, upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
